services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user_service
      - cart_service

  user_service:
    build: ./src/services/user_service
    ports:
      - "4550:8000"

  cart_service:
    build: ./src/services/cart_service
    ports:
      - "4501:8000"
